### PR TITLE
WIP tutorial about pangeo on XSEDE

### PR DESCRIPTION
**Pull request by zonca**
@rsignell-usgs

I'm taking notes as I go here, I'll cleanup later, but in the meantime you can check what I am doing.

Now I can launch `dask` and launch jobs on the workers. But for now I am launching `dask` via `helm`.

Now I started working on using <https://github.com/dask/daskernetes> to launch dedicated dask clusters "owned" by each user.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@zonca, awesome!  I was wondering how things were going.

**Comment by zonca** [comment]
see also the `pangeo` branch: https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/pull/3

**Comment by zonca** [comment]
@rsignell-usgs I am testing Rook object storage that provides a S3-like interface, so then I can use S3Map from `dask/s3fs` to save `zarr` files. However it doesn't work, it hangs when I upload files. I'll follow up next Thursday.

**Comment by rsignell-usgs** [comment]
OK, sounds like progress! Great esip tech talk yesterday on Zarr. Check esipfed Youtube channel for the  recording . Well worth watching!

**Comment by rsignell-usgs** [comment]
https://youtu.be/np_p4JBAIYI

**Comment by zonca** [comment]
Thanks it was very helpful

**Comment by zonca** [comment]
@rsignell-usgs I'm writing 2 papers for PEARC18 these weeks so no much time. As Rook was not working, I gave it a try to use the object storage provided by Jetstream, it worked! See: https://gist.github.com/zonca/071bbd8cbb9d15b1789865acb9e66de8

I can save data with `zarr` to that object storage in a "bucket" (or container in OpenStack parlance) I created through Horizon at https://iu.jetstream-cloud.org/project/containers/. The main issue is that everybody can read, but only people with Jetstream API access can write. How do you think this will work for your use-case?

**Comment by zonca** [comment]
@rsignell-usgs I have for now the shared dask cluster working, I'll publish this tutorial, next I'll work on the user by user cluster

**Pull request merged**
